title: Bevestig weerstanden en jumperdraden aan een LED met soldeer en krimpkous
hero_image: images/banner.png
description: led-weerstand-soldeer-hitte-krimp beschrijving
version: 4
listed: false
copyedit: false
last_tested: "2022-02-07"
steps:
  - 
    title: Inleiding
