title: Attach resistors and jumper wires to an LED with solder and heat shrink
hero_image: images/banner.png
description: led-resistor-solder-heat-shrink description
version: 4
listed: false
copyedit: false
last_tested: "2022-02-07"
steps:
  - 
    title: Introduction
