title: قم بتوصيل المقاومات وأسلاك التوصيل بمتصل مضيء LED مع لحام وشرنك حراري (وهو عبارة عن أنبوب بلاستيكي يتقلص بالحرارة لحماية الاسلاك)
hero_image: images/banner.png
description: وصف متصل مضيء-مقاومة-لحام-شرنك حراري (وهو عبارة عن أنبوب بلاستيكي يتقلص بالحرارة لحماية الاسلاك)
version: 4
listed: false
copyedit: false
last_tested: "2022-02-07"
steps:
  - 
    title: المقدمة
