---
title: Fäst motstånd och byglingskablar till en lysdiod med lödning och krympslang
hero_image: images/banner.png
description: lysdiod-motstånd-löd-krympslang beskrivning
version: 4
listed: false
copyedit: false
last_tested: "2022-02-07"
steps:
  - title: Introduktion
