---
title: Σύνδεσε αντιστάσεις και καλώδια jumper σε ένα LED με συγκόλληση και θερμική συρρίκνωση
hero_image: images/banner.png
description: περιγραφή led-αντίσταση-συγκόλληση-θερμότητα-συρρίκνωση
version: 4
listed: false
copyedit: false
last_tested: "2022-02-07"
steps:
  - title: Εισαγωγή
