title: Fixer des résistances et des fils de connexion à une LED avec de la soudure et de la gaine thermorétractable
hero_image: images/banner.png
description: Description led-résistance-soudure-gaine-thermorétractable
version: 4
listed: false
copyedit: false
last_tested: "2022-02-07"
steps:
  - 
    title: Introduction
